version: "3.8"
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes: ["./backend:/code"]
    env_file: ./backend/.env
  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm i && npm run dev -- --host"
    volumes: ["./frontend:/app"]
    ports: ["5173:5173"]
    depends_on: [backend]
